name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: get_version
        uses: battila7/get-version-action@v2
      - uses: docker/build-push-action@v2
        with:
          build-args: |
            VERSION=${{ steps.get_version.outputs.version-without-v }}
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/kobtea/mixcli:latest
            ghcr.io/kobtea/mixcli:v${{ steps.get_version.outputs.major }}
            ghcr.io/kobtea/mixcli:${{ steps.get_version.outputs.version }}
